version: 0.2

phases:
  install:
    commands:
      - echo Installing aws-cli
      - sudo rm -rf /usr/local/aws
      - sudo rm /usr/local/bin/aws
      - sudo rm /usr/local/bin/aws_completer
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -u awscliv2.zip
      - sudo ./aws/install --update
      - sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
      - aws --version
      - aws configure set aws_access_key_id AKIA34USO4JZGVR3R7O2
      - aws configure set aws_secret_access_key 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
      - aws configure set default.region us-east-1
      - sudo yum install -y net-tools
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 817424687730.dkr.ecr.us-east-1.amazonaws.com
      #- echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  build:
    commands:
      - docker pull 817424687730.dkr.ecr.us-east-1.amazonaws.com/testing1:latest
      - docker images
      - docker run --name "c1" -p 3000:3000 -dt 817424687730.dkr.ecr.us-east-1.amazonaws.com/testing1:latest
      - docker exec c1 sh
      - git clone https://github.com/aditya-sridhar/simple-reactjs-app.git
      - cd simple-reactjs-app
      - npm install
      - npm install -g pm2
      - pm2 start npm -- start
      - pm2 status
      - exit
      - netstat -tunlp | grep 3000
